import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

// Tokens del sistema de diseño de Google Stitch (design/stitch/pa_donde_natty/DESIGN.md).
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9ff",
        primary: "#03224d",
        "inverse-primary": "#afc6fb",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-background": "#111c2d",
        "surface-tint": "#475e8c",
        "surface-container-high": "#dee8ff",
        "surface-variant": "#d8e3fb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "surface-dim": "#cfdaf2",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#e0e3e5",
        "secondary-container": "#d0e1fb",
        "on-primary-container": "#8ba2d5",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#2e4673",
        surface: "#f9f9ff",
        "on-secondary-fixed-variant": "#38485d",
        tertiary: "#202425",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c6d0",
        "on-secondary-container": "#54647a",
        "tertiary-container": "#36393b",
        error: "#ba1a1a",
        "on-primary-fixed": "#001a41",
        secondary: "#505f76",
        "on-surface": "#111c2d",
        outline: "#747780",
        "on-tertiary-container": "#a0a2a4",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-highest": "#d8e3fb",
        "surface-container": "#e7eeff",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#444749",
        "on-surface-variant": "#44474f",
        "inverse-on-surface": "#ecf1ff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        background: "#f9f9ff",
        "inverse-surface": "#263143",
        "primary-fixed-dim": "#afc6fb",
        "surface-container-low": "#f0f3ff",
        "primary-container": "#1f3864",
        // Colores semánticos de estado (tablas/badges del dashboard)
        "success-bg": "#dcfce7",
        "success-fg": "#166534",
        "warning-bg": "#fef3c7",
        "warning-fg": "#92400e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        md: "16px",
        "sidebar-width": "260px",
        "container-max": "1440px",
        xs: "4px",
        xl: "32px",
        xxl: "48px",
        base: "4px",
        sm: "8px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-work-sans)", "sans-serif"],
        "headline-lg": ["var(--font-work-sans)", "sans-serif"],
        "headline-md": ["var(--font-work-sans)", "sans-serif"],
        "display-lg": ["var(--font-work-sans)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "data-mono": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms],
};

export default config;
